defaults: &defaults
  entityPrefix: revolve_
  host: localhost
  logging: false
  password: revolve
  port: 5432
  type: postgres
  username: revolve

development:
  <<: *defaults
  cli:
    entitiesDir: src/entity
    migrationsDir: src/db/migration
  database: revolve_development
  entities:
    - dist/entity/**/*.js
  migrations:
    - dist/db/migration/*.js
  migrationsTableName: revolve_migration
  synchronize: false

test:
  <<: *defaults
  database: revolve_test
  dropSchema: true
  entities:
    - src/entity/**/*.ts
  synchronize: true
